### ISSUE TITLE
problem with getMNVCounts

### ISSUE THREAD

**Issue by riccardobergamin** [danro9685/RESOLVE#4]
When i run getMNVCounts i get the message :
"There are some REF or ALT bases, that do not belong to any of the categories. 
Did you forget to use 'get_dbs_context()'?"

should i filter indels before running it? I am getting the error frequently. In general, are DBS intended as two consecutive SNVs?

**Comment by danro9685** [comment]
Dear @riccardobergamin,
I think so, please refer to this: https://bioconductor.org/packages/release/bioc/manuals/MutationalPatterns/man/MutationalPatterns.pdf
All the best,
Daniele
